id: IB469B70B
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T09:23:06.756534'
last_modified: '2022-06-19T09:23:06.756545'
parser: null
source_metadata:
  title: Supplement to the Autobiography of lCe btsun mkhyen rab byams pa Ngag dbang
    lhun grub (1633–1703); Lamdre Lobshe, vol. ca, title no. 3
  author: ངག་དབང་མཁྱེན་བརྩེའི་རབ་བརྟན།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-09-04);
    unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), ཀུན་དགའ་རྡོ་རྗེ། (Kathmandu) (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/575
  bases:
    9c10:
      title: Supplement to the Autobiography of lCe btsun mkhyen rab byams pa Ngag
        dbang lhun grub (1633–1703); Lamdre Lobshe, vol. ca, title no. 3
      order: 1
      base_file: 9c10.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
